# Generated by Django 2.1 on 2020-01-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorpallete',
            name='is_public',
        ),
        migrations.AddField(
            model_name='colorpallete',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
